/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sims;

/**
 *
 * @author BHUBAN
 */
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
        jComboCategory.setVisible(false);
        category.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        center = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        IDinput = new javax.swing.JTextField();
        jComboCategory = new javax.swing.JComboBox();
        bLogin = new javax.swing.JButton();
        passInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        center.setBorder(BorderFactory.createTitledBorder("LOGIN"));

        ID.setText("User ID: ");

        pass.setText("Password: ");

        category.setText("Category: ");

        jComboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Professor", "Administrator" }));

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        passInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass)
                            .addComponent(category))
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category)
                    .addComponent(jComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogin)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        try {
            int c=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=null;
            con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SIMS","root","");
            if(con==null)
                JOptionPane.showMessageDialog(this, "Unable to Connect to server!!!");
            jComboCategory.setSelectedIndex(0);
            if(jComboCategory.getSelectedIndex()==0)
            {
                String query="select * from sLogin where id='"+IDinput.getText()+"' and pass='"+passInput.getText()+"'";
                System.out.println(query);
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                rs.last();
                if(rs.getRow()==0)
                {
                    //JOptionPane.showMessageDialog(this, "Incorrect userID or password...");
                    jComboCategory.setSelectedIndex(1);
                    c++;
                }
                rs.beforeFirst();
                while(rs.next())
                {
                    System.out.println(rs.getString("id"));
                    System.out.println(rs.getString("pass"));
                    if(IDinput.getText().equals(rs.getString("id")) && passInput.getText().equals(rs.getString("pass"))){
                        System.out.println("registered student");
                        new SHP(passInput.getText().toString(),IDinput.getText().toString()).setVisible(true);
                        dispose();
                    }
                }
            }
            if(jComboCategory.getSelectedIndex()==1)
            {
                String query="select * from pLogin where name='"+IDinput.getText()+"' and pass='"+passInput.getText()+"'";
                System.out.println(query);
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                rs.last();
                if(rs.getRow()==0)
                {
                    //JOptionPane.showMessageDialog(this, "Incorrect userID or password...");
                    jComboCategory.setSelectedIndex(2);
                    c++;
                }
                rs.beforeFirst();
                while(rs.next())
                {
                    System.out.println(rs.getString("name"));
                    System.out.println(rs.getString("pass"));
                    if(IDinput.getText().equals(rs.getString("name")) && passInput.getText().equals(rs.getString("pass"))){
                        System.out.println("registered professor");
                        new PHP(rs.getString("name")).setVisible(true);
                        dispose();
                    }
                }
            }
            if(jComboCategory.getSelectedIndex()==2)
            {
                String query="select * from aLogin where name='"+IDinput.getText()+"' and pass='"+passInput.getText()+"'";
                System.out.println(query);
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                rs.last();
                if(rs.getRow()==0)
                {
                    //JOptionPane.showMessageDialog(this, "Incorrect userID or password...");
                    jComboCategory.setSelectedIndex(0);
                    c++;
                }
                rs.beforeFirst();
                while(rs.next())
                {
                    System.out.println(rs.getString("name"));
                    System.out.println(rs.getString("pass"));
                    if(IDinput.getText().equals(rs.getString("name")) && passInput.getText().equals(rs.getString("pass"))){
                        System.out.println("registered admin");
                        new AHP().setVisible(true);
                        dispose();
                    }
                }  
            }
            if(c==3)
                JOptionPane.showMessageDialog(this, "Incorrect userID or password...");
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void passInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDinput;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel category;
    private javax.swing.JPanel center;
    private javax.swing.JComboBox jComboCategory;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passInput;
    // End of variables declaration//GEN-END:variables
}
